---
- name: backup config
  hosts: all
  gather_facts: false
  connection: local

  tasks:
   - name: show run
     ios_command:
        commands:
         - show run
        host: "{{ inventory_hostname }}"
        username: Groupadmin
        password: W0rk1nNetw0rk$
